export const TASK_ACTIONS = {
    SET_TASK: "SET-TASK",
    ADD_TASK: "ADD-TASK",
    DELETE_TASK: "DELETE-TASK",
    UPDATE_STATUS: "UPDATE-STATUS",
    DELETE_ASYNC: "DELETE-ASYNC",
    DELETE_TASK_IN_PROGRESS: "DELETE-TASK-IN-PROGRESS",
};